# Generated by Django 4.1.3 on 2022-11-28 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_ves'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ves',
            new_name='weight',
        ),
    ]
