# Generated by Django 4.1.3 on 2022-12-05 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_status_productinstance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': ('Компания',), 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='productinstance',
            options={'verbose_name': ('Инвентарный номер',), 'verbose_name_plural': 'Инвентарные номера'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': ('Статус',), 'verbose_name_plural': 'Статусы'},
        ),
    ]
